dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
    - stage: test
      name: Run unit tests
      script: make docker/run target=pytest/lambda/tests
    - stage: test
      name: Run integration tests against a mock AWS stack
      install:
        - make docker-compose/install
        - make mockstack/up
      script: make mockstack/pytest/lambda
      after_script: make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-org-new-account-support-case
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-org-new-account-support-case v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-org-new-account-support-case/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: HuGP8E/Mh4IfQg08ot++SfZPb5ydFtkRJ0fOQAL92hZJgqxODT4eqFQhGFd5OjNfRgBDuEIvU4E0NrE7a87yDXcz/56h3rdzXjtNIFTzFSg015Ult4i8ponU6PNqY8fQ9Zc908GQRviA9X8HHYK/HgoFir59a0CWg4LRf/AbO5XPlWtJlgTpPmt1nuoabwOhermx0dkrAlkVzLKFNDjAaAHQmoQAqVNQM1PZmkl7illAHcW8M47nKQApp4uNjCFz5wX8gcfLTG9hnBU93kZM70mLJjBJxcwnqCUScX46JPBQqXYSlii6OSXg3xyMOa0ThYFEBrb9KReKUmlcowEE0g/cQaazIOQZTxmnPqSX7X7vhZykfloTO1UIzmI3chvHKxN0rzaCLXvypGcgcAYarCsBEqHuaPAToerL6rFiRRB3W9xgw4r51NQTXDAmYKKKvnkMfP3OSnwRAqJu4XtWJFdqQ6Y0oXxE92MUAqJWP6s9Tbq4L2anU91fJpJwvqlA90MmGsciwXGQbRL1JsIGG3OP4uw7/7QLkQA6Hp/nGaQOw3RxaF/u0qKkVGHE0BewDq4JrRXNQvmm01eEiDpoYB2zyWlQbCUPfIy8tCFy+DLeq23wNObAeTSSJjGnJ/eG0Sz+FpL4+dLzI1y35HSEuEuFHgPXuGLdocTbYh1wyZ4=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-org-new-account-support-case
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
